### ISSUE TITLE
Error administrador de comentarios

### ISSUE THREAD

**Issue by AliciaResendiz** [calonso-conabio/buscador#319]
Desde hace tres días no puedo entrar a administrar los comentarios, sale un error.

**Comment by calonso-conabio** [comment]
Una disculpa ya se resolvio, mandé un correo al respecto.

Saludos.

**Comment by SaoriMaitreya** [comment]
Carlos, sigo sin poder administrar comentarios en Enciclovida, saludos! 

----- Mensaje original -----

De: "Carlos Alonso" <notifications@github.com> 
Para: "calonso-conabio/buscador" <buscador@noreply.github.com> 
CC: "SaoriMaitreya" <mresendiz@conabio.gob.mx>, "Author" <author@noreply.github.com> 
Enviados: Lunes, 27 de Agosto 2018 21:13:47 
Asunto: Re: [calonso-conabio/buscador] Error administrador de comentarios (#319) 



Una disculpa ya se resolvio, mandé un correo al respecto. 

Saludos. 

— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 



-- 
Biól. Martha Alicia Reséndiz López 
Especialista de Catálogos de Autoridades Taxonómicas 
martha.resendiz@conabio.gob.mx | Tel. 5004.4942 

Comisión Nacional para el Conocimiento 
y Uso de la Biodiversidad 
Liga Periférico - Insurgentes Sur, Núm. 4903, 
Col. Parques del Pedregal, Delegación Tlalpan, 
C.P. 14010, México, D.F. | Tel. 5004.5000 

www.conabio.gob.mx | www.biodiversidad.gob.mx 
Facebook | Twitter | YouTube

**Comment by albertoglezba** [comment]
Hola Saori, podrías mandarnos por correo una pantalla del error q te sale por favor?
Adicional a esto, podrías limpiar tu cache, cookies y asegurar que las tengas habilitadas, por favor!

Saludos

**Comment by SaoriMaitreya** [comment]
Ya limpié y tengo habilitado lo que indicas, adjunto la pantalla de error, saludos. 

----- Mensaje original -----

De: "Alberto González B." <notifications@github.com> 
Para: "calonso-conabio/buscador" <buscador@noreply.github.com> 
CC: "SaoriMaitreya" <mresendiz@conabio.gob.mx>, "Author" <author@noreply.github.com> 
Enviados: Martes, 28 de Agosto 2018 15:37:32 
Asunto: Re: [calonso-conabio/buscador] Error administrador de comentarios (#319) 



Hola Saori, podrías mandarnos por correo una pantalla del error q te sale por favor? 
Adicional a esto, podrías limpiar tu cache, cookies y asegurar que las tengas habilitadas, por favor! 

Saludos 

— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 



-- 
Biól. Martha Alicia Reséndiz López 
Especialista de Catálogos de Autoridades Taxonómicas 
martha.resendiz@conabio.gob.mx | Tel. 5004.4942 

Comisión Nacional para el Conocimiento 
y Uso de la Biodiversidad 
Liga Periférico - Insurgentes Sur, Núm. 4903, 
Col. Parques del Pedregal, Delegación Tlalpan, 
C.P. 14010, México, D.F. | Tel. 5004.5000 

www.conabio.gob.mx | www.biodiversidad.gob.mx 
Facebook | Twitter | YouTube

**Comment by albertoglezba** [comment]
La pantalla mándala a nuestro correo por favor.

**Comment by albertoglezba** [comment]
Hola Saori, puedes intentar de nuevo, acabamos de subir unos parches al respecto :)
